### ISSUE TITLE
Cannot detect custom `policybundle`

### ISSUE THREAD

**Issue by drewmullen** [mondoohq/packer-plugin-cnspec#101]
I'm trying to write some basic custom checks that will run as part of my packer build. Following the [policy author guide](https://mondoo.com/docs/cnspec/cnspec-policies/write/simple/) i basically just copy / pasted the [file](https://mondoo.com/docs/cnspec/cnspec-policies/write/simple/#a-very-simple-policy-bundle) into a dir just to see if it would run...

```
$ tree
.
|-- README.md
|-- centos
|   |-- centos.pkr.hcl
|   `-- variables.pkr.hcl
|-- cnspec-tests
|   `-- buildtime_check.mql.yaml

# packer run command im using
$ packer build ./centos
```

provisioner definition:
```
 provisioner "cnspec" {
    policybundle = "${path.root}/../cnspec-tests/" 
    # also tried w/o a trailing slash
    # also tried with file name like:
    # "${path.root}/../cnspec-tests/buildtime_check.mql.yaml" 
   
    score_threshold = 1
  }
```

Output:
```
==> azure-arm.centos: Running cnspec packer provisioner by Mondoo (Version: 8.0.1, Build: 0f7366c)
    azure-arm.centos: detected packer build via ssh
    azure-arm.centos: load policy bundle from: ./centos/../cnspec-tests/
    azure-arm.centos: no configuration provided
    azure-arm.centos: scan packer build in incognito mode
    azure-arm.centos: scan completed successfully
    azure-arm.centos: Asset: pkrvmycnnkad0fq
    azure-arm.centos: ----------------------
    azure-arm.centos: 
    azure-arm.centos: error: bundle doesn't contain any policies
    azure-arm.centos: 
    azure-arm.centos: The following policies are available:
    azure-arm.centos: - 
    azure-arm.centos: 
    azure-arm.centos: User selected policies that are allowed to run:
    azure-arm.centos: -
```

even though i posted the `tree` above, just to show that the file is where cnspec is looking

```
$ ll ./centos/../cnspec-tests/
-rw-r--r--  1 root root 725 Apr 10 18:11 buildtime_check.mql.yaml
```

**Comment by drewmullen** [comment]
```
$ cat cnspec-tests/buildtime_check.mql.yaml 
policies:
  - uid: buildtime-file-exists
    name: Check if packer buildtime file was created by Ansible
    version: "1.0.0"
    scoring_system: highest impact
    authors:
      - name: dm
        email: <redacted>
    groups:
      - checks:
          - uid: sshd-01
            title: Ensure the port is set to 22
            mql: sshd.config.params["Port"] == 22
            impact: 30

          - uid: sshd-02
            title: Prevent weaker CBC ciphers from being used
            mql: sshd.config.ciphers.none( /cbc/ )
            impact: 60

        queries:
          - uid: sshd-d-1
            title: Gather SSH config params
            mql: sshd.config.params
```

**Comment by chris-rock** [comment]
@drewmullen There are a combination of issues here:

1. With the migration to cnspec v8 the policy filters where different. Fix is up here https://github.com/mondoohq/packer-plugin-cnspec/pull/102
2. The defined policy requires a filter

The updated policy:

```
policies:
  - uid: buildtime-file-exists
    name: Check if packer buildtime file was created by Ansible
    version: "1.0.0"
    scoring_system: highest impact
    authors:
      - name: dm
        email: <redacted>
    groups:
      - title: Buildtime checks
        filters:
        - mql: asset.family.contains('unix')
        checks:
          - uid: sshd-01
            title: Ensure the port is set to 22
            mql: sshd.config.params["Port"] == 22
            impact: 30

          - uid: sshd-02
            title: Prevent weaker CBC ciphers from being used
            mql: sshd.config.ciphers.none( /cbc/ )
            impact: 60

        queries:
          - uid: sshd-d-1
            title: Gather SSH config params
            mql: sshd.config.params
```

With both changes, local policy bundles work again:

<img width="962" alt="Screenshot 2023-04-14 at 13 47 19" src="https://user-images.githubusercontent.com/1178413/232035535-63510388-59de-4713-813a-f3fb3e1b67c7.png">
