### ISSUE TITLE
Evaluating mondoo.jobEnvironment['id']

### ISSUE THREAD

**Issue by username-is-already-taken2** [mondoohq/packer-plugin-cnspec#337]
**Describe the bug**
I am unable to use the filter mondoo.jobEnvironment['id'] != "packer.io" as expected.

The issue arises in a scenario where I have a policy containing controls that differ based on whether I'm using the cnspec provisioner. My goal is to use this filter for testing purposes during template creation and subsequently evaluate the condition after deploying a virtual machine with the template. However, the filter no longer seems to work as intended in this context.

**To Reproduce**

I don't expect these checks to be run during a template scan, but they are
```
      - filters: |
          // run on a vm deployed from the template
          asset.platform == "windows"
          mondoo.jobEnvironment['id'] != "packer.io"
        checks:
          - uid: firewall_01
          - uid: hardware_01
          - uid: hardware_02
          - uid: hardware_03
          - uid: windows-user-01
```

**Expected behavior**

**Screenshots or CLI Output**
![Image](https://github.com/user-attachments/assets/69bcc396-139d-48cb-8c4a-8c7d898b832a)
Example of these checks being run during build
